### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by michael-suh** [michael-suh/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create visibility for car
- [x] Create background and set the color for the game
- [x] Set car's starting point to top left
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary 
- [x] Fix all errors
