### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by michael-suh** [michael-suh/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [ ] create a function to start the car
- [ ] move car 
- [ ] hold car's location
- [ ] setInterval for starting the car
- [ ] Make new event listener for keydown event
- [ ] clean up CSS and unnecessary code
- [ ] fix errors
